---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROXY_SERVICE_NAME
  labels:
    app: $PROXY_SERVICE_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $PROXY_SERVICE_NAME
  template:
    metadata:
      labels:
        app: $PROXY_SERVICE_NAME
    spec:
      containers:
      - name: $PROXY_SERVICE_NAME
        image: $PROXY_SERVICE_NAME:$PROXY_VERSION
        ports:
        - containerPort: $PROXY_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: $PROXY_SERVICE_NAME
  labels:
    app: $PROXY_SERVICE_NAME
spec:
  type: LoadBalancer
  selector:
    app: $PROXY_SERVICE_NAME
  ports:
    - name: $PROXY_SERVICE_NAME
      port: $PROXY_PORT
      targetPort: $PROXY_PORT
